### PR TITLE
Us06 hamid alakbarov

### PR DESCRIPTION
**Pull request by hamidalakbarov**
Please review my work, thank you!

### CODE REVIEW

**Review by Daniz2000 — APPROVED** [review]
Great Work :)

**Review by DanSpicica — APPROVED** [review]
Looks great Hamid, I just have a question about the ISBN number of the book, I'll ask you tomorrow...

**Review by SForogh — COMMENTED** [review]
Great job as always!
For some reason, It shows me 72 file changed, is it common?

**Comment by hamidalakbarov** [comment]
> Great job as always! For some reason, It shows me 72 file changed, is it common?

Thank you Sohaila, I am not sure why is it showing 72 files...

**Review by evabaldwin — COMMENTED** [review]
looks great!

**Pull request merged**
