### PR TITLE
US_05 is ready

### PR DESCRIPTION
**Pull request by DanSpicica**
Please review and advise...

### CODE REVIEW

**Review by hamidalakbarov — APPROVED** [review]
Good job Dan & Mahdi! Thank you!

**Review by SForogh — APPROVED** [review]
Great job, Dan & Mahdi.

**Review by vsimpryvit — APPROVED** [review]
Well done !

**Review by LinaVisochin — APPROVED** [review]
Great job!

**Review by latifaforozan — APPROVED** [review]
Great work Dan and Mahdi!

**Pull request merged**
