### PR TITLE
US01 Latifa Forozan

### PR DESCRIPTION
**Pull request by latifaforozan**
US01 completed. UsersStepDefs added.

### CODE REVIEW

**Comment by hamidalakbarov** [comment]
Perfect Latifa!

**Review by SForogh — APPROVED** [review]
Good job!
Liked the implementation of encapsulation in your stepDefs. 👍

**Comment by hamidalakbarov** [comment]
> Good job! Liked the implementation of encapsulation in your stepDefs. 👍

Yes agree, its good idea!

**Review by DanSpicica — APPROVED** [review]

**Comment by hamidalakbarov** [comment]
Merging PR, thank you!

**Pull request merged**
